spring.application.name=medilabosolutionapplication-security
server.port=8087

# Keycloak
keycloak.url.token=http://localhost:8085/realms/medilabosolution/protocol/openid-connect/token
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8085/realms/medilabosolution
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8085/realms/medilabosolution/protocol/openid-connect/certs
logging.level.org.springframework.security=DEBUG
jwt.auth.converter.resource-id=medilabosolution_client
jwt.auth.converter.principal-attribute=principal_username
#jwt.auth.converter.principal-attribute=preferred_username

# Log
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security=DEBUG

log4j.rootLogger=debug, Stdout
log4j.appender.Stdout=org.apache.log4j.ConsoleAppender
log4j.appender.Stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.Stdout.threshold=debug