spring.application.name=medilabosolutionapplication-front

server.port=8082

# FeignClients
#spring.cloud.openfeign.client.medilabosolutionapplicationrisk.url=http://localhost:8080
#spring.cloud.openfeign.client.medilabosolutionapplicationpatient.url=http://localhost:8080
#spring.cloud.openfeign.client.medilabosolutionapplicationnotes.url=http://localhost:8080
spring.cloud.openfeign.client.gateway.url=http://localhost:8080
spring.cloud.openfeign.client.security.url=http://localhost:8087

# Keycloak
#keycloak.url.token=http://localhost:8085/realms/medilabosolution/protocol/openid-connect/token
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8085/realms/medilabosolution
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8085/realms/medilabosolution/protocol/openid-connect/certs
#jwt.auth.converter.resource-id=medilabosolution_client
#jwt.auth.converter.principal-attribute=principal_username

# Utilise X-Forwarded-Host (envoyé par la Gateway) pour construire les URLs de redirect
server.forward-headers-strategy=framework


#logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
#logging.level.org.springframework.security=DEBUG

log4j.rootLogger=debug, Stdout
log4j.appender.Stdout=org.apache.log4j.ConsoleAppender
log4j.appender.Stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.Stdout.threshold=debug

logging.level.org.springframework.web.client.RestTemplate=DEBUG