spring.application.name=medilabosolutionapplication-front

server.port=8082

# FeignClients
#spring.cloud.openfeign.client.medilabosolutionapplicationrisk.url=http://localhost:8080
#spring.cloud.openfeign.client.medilabosolutionapplicationpatient.url=http://localhost:8080
#spring.cloud.openfeign.client.medilabosolutionapplicationnotes.url=http://localhost:8080
spring.cloud.openfeign.client.gateway.url=http://localhost:8080