spring.application.name=medilabosolutionapplication-gateway

server.port=8080

logging.level.org.springframework.cloud.gateway=DEBUG

log4j.rootLogger=debug, Stdout
log4j.appender.Stdout=org.apache.log4j.ConsoleAppender
log4j.appender.Stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.Stdout.threshold=debug

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=medilabosolutionapplication-patient
spring.cloud.gateway.routes[0].uri=http://localhost:8081/
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/patients/**

spring.cloud.gateway.routes[1].id=medilabosolutionapplication-notes
spring.cloud.gateway.routes[1].uri=http://localhost:8083/
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/notes/**

spring.cloud.gateway.routes[2].id=medilabosolutionapplication-risk
spring.cloud.gateway.routes[2].uri=http://localhost:8084/
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/risk/**

spring.cloud.gateway.routes[3].id=medilabosolutionapplication-front
spring.cloud.gateway.routes[3].uri=http://localhost:8082/
spring.cloud.gateway.routes[3].predicates[0]=Path=/login,/patient/**,/risk/**,/notes/**,/

spring.cloud.gateway.routes[4].id=medilabosolutionapplication-security
spring.cloud.gateway.routes[4].uri=http://localhost:8087/
spring.cloud.gateway.routes[4].predicates[0]=Path=/auth/**

security.service.url=http://localhost:8087/