spring.application.name=medilabosolutionapplication-patient

# BDD
spring.datasource.url=jdbc:mysql://localhost:3306/medilabosolution?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rootroot
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
 
server.port=8081

security.service.url=http://localhost:8087/
 #commentaire



logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security=DEBUG