spring.application.name=medilabosolutionapplication-patient

# BDD
spring.datasource.url=jdbc:mysql://localhost:3306/medilabosolutionTest?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rootroot
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
 
server.port=8081

# Option Hibernate pour créer/détruire le schéma à chaque démarrage
spring.jpa.hibernate.ddl-auto=create-drop
 
 #commentaire

