spring.application.name=medilabosolutionapplication_risk
server.port=8084

# FeignClients
#spring.cloud.openfeign.client.medilabosolutionapplicationnotes.url=http://localhost:8080
#spring.cloud.openfeign.client.medilabosolutionapplicationpatient.url=http://localhost:8080
spring.cloud.openfeign.client.gateway.url=http://localhost:8080