spring.application.name=medilabosolutionapplication_risk
server.port=8084

# FeignClients
spring.cloud.openfeign.client.patient.url=http://localhost:8081
spring.cloud.openfeign.client.notes.url=http://localhost:8083


security.service.url=http://localhost:8087/